#!/usr/bin/env bash
set -euo pipefail

# Quick rotate helper — DOES NOT rotate provider-side API keys (Google/Stytch).
# Use this script to generate new local secrets and prepare a `.env.new` file.
# After generating new provider keys (Google Cloud / Stytch), update the
# corresponding values in .env.new and swap into place.

OUT=.env.new
BACKUP=.env.bak.$(date +%s)

cat > "$OUT" <<'EOF'
# Generated by scripts/rotate_keys.sh — update provider keys where noted
API_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ADMIN_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
# STYTCH_SECRET: Replace with value from Stytch dashboard
STYTCH_SECRET=
# YT_KEY: Replace with new YouTube Data API key from Google Cloud
YT_KEY=
# Admin phone (leave as-is if unchanged)
ADMIN_PHONE_NUM=
REFRESH_INTERVAL=1800
STABLE_REFRESH_INTERVAL=21600
EOF

printf "Created %s (preview):\n\n" "$OUT"
sed -n '1,200p' "$OUT"

cat <<'MSG'

Next steps (manual):
 1. Rotate provider keys:
    - Google Cloud Console: create/disable YouTube API keys as needed.
    - Stytch dashboard: rotate secrets if required.
 2. Edit .env.new and fill in STYTCH_SECRET and YT_KEY.
 3. Backup current .env and move .env.new into place:
      cp .env "${BACKUP}"
      mv .env.new .env
 4. Restart services (example using Docker Compose):
      docker compose down && docker compose up -d --build
 5. Verify admin login and background poller behavior.
 6. Revoke old provider keys in their respective consoles.

Security notes:
 - Do NOT commit .env to git. Ensure .gitignore contains ".env".
 - Use a secrets manager (Railway, AWS Secrets Manager, Terraform Cloud variables) for production.

MSG
